[build]
  Command = "yarn build"
  Functions = "lambda"
  Publish = "dist"
  
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

[[redirects]]
from = "/api/employees/*"
to = "https://www.humanity.com/api/v2/:splat"
status = 200
force = false

[[redirects]]
from = "/api/assets/*"
to = "https://www.humanity.com/api/v2/:splat"
status = 200
force = false